WebSiteAPI.UI/ViewComponents/MenuCategoryViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using WebSiteAPI.Application.Abstractions.Service;

namespace WebSiteAPI.UI.ViewComponents
{
    public class MenuCategoryViewComponent: ViewComponent
    {readonly ICategoryService _categoryService;

        public MenuCategoryViewComponent(ICategoryService categoryService)
        {
            _categoryService = categoryService;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            var categories =await _categoryService.GetAllAsync();
            return View(categories);
        }
       
    }
}

WebSiteAPI.UI/Views/Shared/_Layout.cshtml
@using WebSiteAPI.Persistence.Contexts;
@using WebSiteAPI.Persistence.Services;
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebSiteAPI.UI</title>
    <link rel="stylesheet" media="all" href="/WebSite/css/bootstrap.css" />
    <link rel="stylesheet" media="all" href="/WebSite/css/animate.css" />
    <link rel="stylesheet" media="all" href="/WebSite/css/font-awesome.css" />
    <link rel="stylesheet" media="all" href="/WebSite/css/furniture-icons.css" />
    <link rel="stylesheet" media="all" href="/WebSite/css/linear-icons.css" />
    <link rel="stylesheet" media="all" href="/WebSite/css/magnific-popup.css" />
    <link rel="stylesheet" media="all" href="/WebSite/css/owl.carousel.css" />
    <link rel="stylesheet" media="all" href="/WebSite/css/ion-range-slider.css" />
    <link rel="stylesheet" media="all" href="/WebSite/css/theme.css" />
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,500,600&amp;subset=latin-ext" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500" rel="stylesheet">

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>
<body>
    <nav class="navbar-fixed">
        <div class="container">
            <div class="navigation navigation-top clearfix">
                <ul>
                    <li><a href="#"><i class="fa fa-facebook"></i></a></li>
                    <li><a href="#"><i class="fa fa-twitter"></i></a></li>
                    <li><a href="#"><i class="fa fa-youtube"></i></a></li>
                </ul>
            </div>
            <div class="navigation navigation-main">
                <a href="index.html" class="logo"><img src="assets/images/logo.png" alt="" /></a>
                <a href="#" class="open-menu"><i class="icon icon-menu"></i></a>
                <div class="floating-menu">
                    <div class="close-menu-wrapper">
                        <span class="close-menu"><i class="icon icon-cross"></i></span>
                    </div>
                    <ul>
                        <li><a href="/">Anasayfa</a></li>    
                        @await Component.InvokeAsync("MenuCategory")
                        <li><a href="#">Hakkımızda</a></li>
                        <li><a href="/contact">İletişim</a></li>
                    </ul>
                </div>
            </div>
        </div>
    </nav>
    @RenderBody()
    <footer>
        <div class="container">
            <div class="footer-showroom">
                <div class="row">
                    <div class="col-sm-8">
                        <h2 style="text-transform:capitalize; ">Mağazamızı Ziyaret Edin</h2>
                        <p>Ihlamurkuyu, Arife Sk No:3/ B, 34771 Ümraniye/İstanbul</p>
                    </div>
                    <div class="col-sm-4 text-center">
                        <div class="call-us h4"><span class="icon icon-phone-handset"></span> 0 505 978 9407</div>
                    </div>
                </div>
            </div>
            <div class="footer-links">
                <div class="row">
                    <div class="col-sm-4 col-md-2">
                        <h5>Browse by</h5>
                        <ul>
                            <li><a href="#">Anasayfa</a></li>
                            <li><a href="#">Ürünler</a></li>
                        </ul>
                    </div>
                    <div class="col-sm-4 col-md-2">
                        <h5>Ürünler</h5>
                        <ul>
                            <li><a href="#">Fileli Koltuk</a></li>
                            <li><a href="#">Ofis Koltukları</a></li>
                            <li><a href="#">Bahçe Koltukları</a></li>
                        </ul>
                    </div>
                    <div class="col-sm-4 col-md-2">
                        <h5>Our company</h5>
                        <ul>
                            <li><a href="#">Hakkımızda</a></li>
                            <li><a href="#">İletişim</a></li>
                        </ul>
                    </div>
                    <div class="col-sm-12 col-md-6">
                        <h5 style="text-transform:capitalize">Yeni Ürünlerimizden haberdar olun</h5>
                        <p><i>E-posta adresinizi ekleyerek aylık e-postalarımıza kaydolabilir ve promosyon tekliflerini alabilirsiniz</i></p>
                        <div class="form-group form-newsletter">
                            <input class="form-control" type="text" name="email" value="" placeholder="Email address" />
                            <input type="submit" class="btn btn-clean btn-sm" value="Haberdar Ol" />
                        </div>
                    </div>
                </div>
            </div>
            <div class="footer-social">
                <div class="row">
                    <div class="col-sm-6">
                         |  OukSoft <a href="#">Tüm Haklar Saklıdır.</a>
                    </div>
                    <div class="col-sm-6 links">
                        <ul>
                            <li><a href="https://www.facebook.com/OdayFurniture" target="_blank"><i class="fa fa-facebook"></i></a></li>
                            <li><a href="https://www.instagram.com/oday.furniture/" target="_blank"><i class="fa fa-instagram"></i></a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </footer>
    <script src="/WebSite/js/jquery.min.js"></script>
    <script src="/WebSite/js/jquery.bootstrap.js"></script>
    <script src="/WebSite/js/jquery.magnific-popup.js"></script>
    <script src="/WebSite/js/jquery.owl.carousel.js"></script>
    <script src="/WebSite/js/jquery.ion.rangeSlider.js"></script>
    <script src="/WebSite/js/jquery.isotope.pkgd.js"></script>
    <script src="/WebSite/js/main.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>